name: Task Tracker CI/CD

on:
  push:
    branches: [main]  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install dependencies (for testing)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Django tests (if you have any)
      - name: Run tests
        run: |
          python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: TaskTracker.settings

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t petercodes24/task-tracker:latest .
          docker push petercodes24/task-tracker:latest